#!/bin/sh -e

echo "building with docker. might take a while to pull..."
docker run --rm -v `pwd`:/usr/src/vulcan-sidekick -w /usr/src/vulcan-sidekick golang:1.3.3 ./build

echo "building docker image..."
docker build -t robszumski.com:5000/vulcan-sidekick .

echo "done"
